[build]
  publish = "dist/portfolio-camilo/browser"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:prod"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
